// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgyqfxcuoihsvrwhxukd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpneXFmeGN1b2loc3Zyd2h4dWtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3ODA1NDEsImV4cCI6MjA3MDM1NjU0MX0.ZqlEYiEd7BzyAz_4bxFP86gAKHqi74mHhNYC_rkErWY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});